name: Deploy Automático a DigitalOcean

on:
  push:
    branches:
      - main # O la rama que uses (ej. master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar Git Pull en el Servidor
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/allpafood.com/Allpa-food-/
            git pull origin main